name: 'Apache syntax checker'

description: 'Runs the apache configuration check'
# inputs:
#   branch-name:
#     description: 'Branch name that does pull request'
#     required: true
# outputs:
#   result:
#     description: 'The result of the test'

# runs:
#   using: 'docker'
#   image: 'Dockerfile'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action_script.sh
      shell: bash

  # args:
    # - ${{ inputs.branch-name }}
